services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=ewm-stats
      - SPRING_DATASOURCE_PASSWORD=ewm-stats

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm-stats
      - POSTGRES_USER=ewm-stats
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10