services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=ewm-stats
      - SPRING_DATASOURCE_PASSWORD=ewm-stats

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm-stats
      - POSTGRES_USER=ewm-stats
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EWM_STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm-db
      - SPRING_DATASOURCE_PASSWORD=ewm-db

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=ewm-db
      - POSTGRES_USER=ewm-db
      - POSTGRES_DB=ewm-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10