spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/stats_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validated
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    sql: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

server:
  port: 9090